name: Domain Resolution

on:
  push:
    branches:
      - main

jobs:
  resolve_domain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run domain resolver script
        run: bash ./dns_resolver.sh
