name: Run PHP script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
          extensions: curl
      - run: php $GITHUB_WORKSPACE/location-update.php
