name: DNS Resolution

on:
  push:
    branches:
      - main

jobs:
  resolve_dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send DNS resolution request
        uses: actions/http-request@v2
        with:
          url: 'https://dns.google/resolve?name=cc220ed01053.sn.mynetname.net&type=A'
          method: GET

      - name: Display DNS resolution result
        run: |
          echo ${{ steps.send_dns_resolution_request.outputs.response_body }}
