name: DNS Resolution

on:
  workflow_dispatch:

jobs:
  resolve_dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send DNS resolution request
        run: |
          apiUrl='https://dns.google/query?name=cc220ed01053.sn.mynetname.net'
          response=$(curl -s "$apiUrl")
          echo "$response"
