name: DNS Resolution

on:
  push:
    branches:
      - main

jobs:
  resolve_dns:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send DNS resolution request
        id: curl
        uses: wei/curl@v1
        with:
          args: -X GET https://dns.google/resolve?name=cc220ed01053.sn.mynetname.net&type=A


      - name: Display DNS resolution result
        run: |
          echo ${{ steps.curl.outputs.response }} # Sử dụng id để truy cập kết quả
